default_config:

logger:
  default: info
  logs:
    custom_components.narodmon: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

narodmon:
  apikey: "51KUfP4TRQsU9"
  devices:
    - name: "Narodmon"
      sensors:
        - temperature
        - humidity
