default_config:

logger:
  default: info
  logs:
    custom_components.narodmon: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

narodmon:
  devices:
    - name: "Narodmon"
#      sensors:
#        - temperature
#        - humidity
      scan_interval:
        seconds: 61
